### ISSUE TITLE
请问运行脚本后报这个错怎么办，用的是方法2

### ISSUE THREAD

**Issue by sirenions** [yukinotech/qBittorrent-block-xunlei#1]
![{J`8R7A@W(LYZJ64PS$7OHS](https://user-images.githubusercontent.com/77059338/190163184-e34a9fa9-e934-41f5-8cff-25d022aa4b1e.png)

**Comment by sirenions** [comment]
qbittorrent版本4.1.9.1 x64

**Comment by yukinotech** [comment]
> 

一应该是一次执行的过程中失败了，但是不影响下一次的执行。问一下，脚本里显示屏蔽的内容成功屏蔽了吗？如果成功了可以忽略这个报错

**Comment by sirenions** [comment]
> > 
> 
> 一应该是一次执行的过程中失败了，但是不影响下一次的执行。问一下，脚本里显示屏蔽的内容成功屏蔽了吗？如果成功了可以忽略这个报错

除了报错的ip不能屏蔽，其他ip都成功屏蔽了。现在脚本可以使用，如果能解决这个报错就更好了

**Comment by yukinotech** [comment]
> > > 
> > 
> > 
> > 一应该是一次执行的过程中失败了，但是不影响下一次的执行。问一下，脚本里显示屏蔽的内容成功屏蔽了吗？如果成功了可以忽略这个报错
> 
> 除了报错的ip不能屏蔽，其他ip都成功屏蔽了。现在脚本可以使用，如果能解决这个报错就更好了

应该是144行`"/api/v2/transfer/banPeers"`报错。我回忆了一下，如果是404的话，应该是这个要屏蔽的用户找不到了。要么是已经被屏蔽了，要么是断开了。按道理应该不会有漏掉的情况。

**Comment by sirenions** [comment]
> > > > 
> > > 
> > > 
> > > 一应该是一次执行的过程中失败了，但是不影响下一次的执行。问一下，脚本里显示屏蔽的内容成功屏蔽了吗？如果成功了可以忽略这个报错
> > 
> > 
> > 除了报错的ip不能屏蔽，其他ip都成功屏蔽了。现在脚本可以使用，如果能解决这个报错就更好了
> 
> 应该是144行`"/api/v2/transfer/banPeers"`报错。我回忆了一下，如果是404的话，应该是这个要屏蔽的用户找不到了。要么是已经被屏蔽了，要么是断开了。按道理应该不会有漏掉的情况。

那就先这样吧，比没有强多了，非常感谢你的插件
